### ISSUE TITLE
Missing network modal notification

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#125]
**Describe the bug**
There is no notification shown to the user when there is a wallet-network mismatch in the application. 

**To Reproduce**
1. Switch the wallet network

**Additional context**
If the network does not match, a user can't vote due to EIP-712.

**Comment by supriyaamisshra** [comment]
Hi !! is this still open, would like to work on it!

**Comment by tricelex** [comment]
I'm currently working on this @supriyaamisshra
