### ISSUE TITLE
Add Token Select component

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#126]
Add bliss's token select component

**Comment by Dhaiwat10** [comment]
@hansmrtn I can help. Could you link me to Bliss's component please?

**Comment by hansmrtn** [comment]
😅 this feature is already added! that being said, it certainly can be improved. checkout the latest dev branch to test it out.

**Comment by Dhaiwat10** [comment]
@xordist oh no worries I can look into it. Is there anything else that I can help with that's more urgent?
