### ISSUE TITLE
Room-like homescreen

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#140]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the usability of the product. Currently, a user is always capable of seeing _every_ party. It is too daunting to expect a user to sift through this.

**Describe the solution you'd like**
We should implement a "room"-like frontend, similar to that of tip.party, where the user is asked to provide an identifier that then navigates the user to the party. 

**Describe alternatives you've considered**
We have considered meta-tags and filter selections. However, this proposal is simpler and consistent. 

**Additional context**
Additionally, we should allow the use to easily create a party.

**Comment by bhargavaparoksham** [comment]
Other Alternative:
As Voters / Candidates are set upfront in a Pay Party unlike in Tip Parties. We can automatically show a filtered view of only the rooms / parties that a user is part of.

**Comment by hansmrtn** [comment]
I think there is certainly room for both approaches. A WIP implementation of the room is [here](https://github.com/hmrtn/pay.party/blob/rooms/packages/react-app/src/routes/home/Home.jsx). By default the user should be asked to join by some identifier. If the user is part of other parties, they should have an option to see a list of those, too. 🙏
