### ISSUE TITLE
Unable to send vote API requests

### ISSUE THREAD

**Issue by QEDK** [moonshotcollective/quadratic-diplomacy#146]
**Describe the bug**
Vote endpoint request errors out with `NS_BINDING_ABORTED`

**To Reproduce**
1. Go to an election
2. Click on 'Vote'
3. Vote is not sent

**Expected behavior**
Vote should be sent

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Firefox v97.0.1

**Comment by hansmrtn** [comment]
It is probably a race condition found from [here](https://github.com/moonshotcollective/pay.party/blob/75a9053fde24bc033784ab6e1e0e356c445b6b48/packages/react-app/src/routes/party/components/VoteTable.jsx#L88), and will be addressed with the latest PR.
