### ISSUE TITLE
As a room creator, I want to click home to and edit in the room creation process in order to go back to home or edit my room.

### ISSUE THREAD

**Issue by brentmartin** [moonshotcollective/quadratic-diplomacy#154]
### Is your feature request related to a problem? Please describe.
Room creator uses the back button to fix an error, which is a bad user experience.

---
### Describe the solution you'd like
When the room creator clicks "create party" to go to the room creation screen, inside of the /create view they can click a "home" button rather than a "back" button that currently exist. It would be helpful if there was a tooltip at this point, pointing out that all information will be deleted when hovering over "home" - but i'll leave that up to the devs to decide.

Subsequently, in the /create screen, when the room creator is reviewing and wants to go back to the "create party" screen - they should click an "edit" button where the current "back" button is.

---
### Describe alternatives you've considered
none really here

---
### Additional context
other stickies related to this one:
- "user is forced to restart their election creation everytime they click 'Back'"
- "user expects to go back edit from review when they click 'back'"
- "user did not see the edit button"
- "Create Party: having to restart a party (after being made) was annoying (not sure if she was using version with review page before). She liked what we did with tip.party (people responsible for signing themselves in)"
- "Review Party: Found edit button (but only after she hit back and started up the party again)"
- "Review Party: When we asked her to add a missing address to the list, she chose to hit Back instead of Edit. Clicking back exited her out of making the room to the "All Room" page and frustrated her that it didn't take her back to the Create Party page."

**Comment by bhargavaparoksham** [comment]
I'm working on this.

**Comment by bhargavaparoksham** [comment]
@hmrtn I've made a pull request to add the above feature request. Please review it. Thanks.

**Comment by brentmartin** [comment]
This ticket is completed, yes?

**Comment by bhargavaparoksham** [comment]
Yes, the PR with the requested changes has been merged.
