### ISSUE TITLE
Payout History does not display without refresh

### ISSUE THREAD

**Issue by ufkhan97** [moonshotcollective/quadratic-diplomacy#180]
@blahkheart and I found this bug today:

**Describe the bug**
There is limited indication that a payout succeeded when distributing funds unless the user manually refreshes 

**To Reproduce**
1. Create a Pay Party and Vote
2. Distribute Funds 
3. Check if payout history appears
4. Refresh and check again

**Expected behavior**
Expected confetti and payout history to load after funds were distributed, without a refresh

**Screenshots**
Please see below 

**Desktop (please complete the following information):**
OS: macOS Monterey 12.0.1
Browser: Chrome
Version: 100.0

**Additional context**

**Comment by blahkheart** [comment]
Find a screen recording below showing the issue
https://user-images.githubusercontent.com/45943555/162794264-eb3e8ca0-ada5-4e0b-8994-750bb3feba89.mp4
