### ISSUE TITLE
ENS names copied from pay party paste as 0x Addresses

### ISSUE THREAD

**Issue by ufkhan97** [moonshotcollective/quadratic-diplomacy#181]
@blahkheart and I found this bug today:

**Describe the bug**
When you copy an ENS name or list of names and paste it elsewhere then it pastes as 0x address 

**To Reproduce**
1. Create a pay party 
2. Load voters and candidates
3. Create a new pay party. Try to copy candidates ENS names from the first pay party
4. Past the address into the new party and it loads as 0x instead of ENS

**Expected behavior**
Expected to paste in ENS names 

**Screenshots**
Please see below

**Desktop (please complete the following information):**
- OS: macOS Monterey 12.0.1
-  Browser: Chrome
- Version: 100.0

**Comment by blahkheart** [comment]
Find a screen recording of the issue below
https://user-images.githubusercontent.com/45943555/162788520-283b422a-24cc-40b0-99d8-34bde61aa447.mp4
