### ISSUE TITLE
Top Banner displayed 'You must switch to Mainnet' but I needed to be on Rinkeby

### ISSUE THREAD

**Issue by ufkhan97** [moonshotcollective/quadratic-diplomacy#185]
**Describe the bug**
Top Banner displayed 'You must switch to Mainnet' but I needed to be on Rinkeby

**To Reproduce**
1. Go to a pay party created on Rinkeby 
2. Be on Mainnet in wallet and app
3. Use 'You Must Switch Network To Vote' button to switch to Rinkeby from mainnet in wallet
4. See Top Banner displays 'You have Rinkeby selected and you need to be on Mainnet'
5. 

**Expected behavior**
Top Banner should say 'You have Mainnet selected (in app) and need to be on Rinkeby'

**Screenshots**

<img width="945" alt="Screen Shot 2022-04-12 at 1 05 58 PM" src="https://user-images.githubusercontent.com/43886242/163016801-843db406-e003-40bf-a543-08cde1d964a1.png">

**Desktop (please complete the following information):**
- OS: macOS Monterey 12.0.1
- Browser: Chrome
- Version: 100.0

**Additional context**

**Comment by gtcsameer** [comment]
Thanks for this issue Umar! Just curious, how is this different from #184; personally, I think these two issues seem to be related to the same bug. Are you just splitting both parts of the bug into two separate issues?

**Comment by ufkhan97** [comment]
I think they're two different bugs but both related to network issues. One
is about the mid-screen network switch banner which doesnt switch your
network. The other is about the top-screen banner that does not correctly
detect the network you're in.

**Comment by blahkheart** [comment]
I took a moment to inspect the bug and what happens is, after clicking the switch network button on the app it switches your network in your wallet to the specified network but it doesn't switch the network of the app to the same network, it remains on the current network, thus causing the new error displayed by the top banner which in this particular case is "You have rinkeby selected and you need to be on Mainnet".
