### ISSUE TITLE
Delineate Candidates/Voters

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#42]
This effort should change up the format of the elections, where voters can be distinct from the candidates.
Currently, every voter is automatically a delegated candidate. 
We need to allow large communities to be able to vote on a specific subset of candidates.

**Comment by damianmarti** [comment]
I made this change on the off-chain version at https://github.com/scaffold-eth/scaffold-eth/tree/qd-off-chain-voters-and-candidates

You have two lists. One for the voters and one for the candidates:

![qdip-create](https://user-images.githubusercontent.com/466652/139733520-727344a1-d030-487d-af94-49916eb5405c.png)

And the rewards page, the information is split too.

![qdip-rewards](https://user-images.githubusercontent.com/466652/139733498-50613649-622a-4fb5-a8a1-d443f901ed55.png)

Maybe we can add a checkbox "Use voters as candidates too" and if you check that you have to fill just one list and if you leave this unchecked, you have the two lists.

@hansmrtn what do you think?
