### ISSUE TITLE
UI: Home Party Cards 

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#61]
The application needs an understandable way to display the multiple parties on the screen with relevant metadata. 

Each party has some metadata like: 
- name 
- creation date
- number of participants
- receipts 
- etc

That could be displayed on a card-like component. The component should be reusable and mobile-ready.

**Comment by wkarshat** [comment]
This component will be replacing the method used to display each of the parties on the Home page. Is PartyCard.jsx the incoming implementation, please?

**Comment by naz3eh** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/56908732/152847197-9798096c-c43c-417d-8521-6afff9b9b16e.png">

Based on the data provided above, I determined that I should display the party's meta data in these cards. I need to develop a new component that is both reusable and responsive (mobile-ready)
