### ISSUE TITLE
UI: Party creation review screen

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#62]
The application should provide more user-feedback and review. We can do this by including a review screen when a user submits a new election. The review screen would be the final step to review the relevant info they are about to submit in the party. 
i.e.
- name
- description
- resolved ens side-by-side plain addresses
- etc

**Comment by wkarshat** [comment]
Is this a Good First Issue [GFI] candidate, please?
Frontend, Node, React, Chakra skills, but what else?
Where would it hook into the existing implementation, what current page looks closest?
