### ISSUE TITLE
UI: Tooltips

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#63]
User feedback is important in a lot of areas of the app. 

We could use tooltips just about everywhere that explain certain things, or show more relevant information.

For example: 

- [ ] Explain candidates, participants on creation
- [ ] Let user know what ens isn't resolved on creation
- [ ] What strategies are
- [ ] Amount being distributed in wei (on TBD distribution view)
- etc

**Comment by wkarshat** [comment]
Tooltip comments need to match the online documentation: taxonomy and verbiage.
Candidates are vote recipients and participants are voters?
Need to update # votes description.
Any text locations, in addition to README.md and https://hackmd.io/Vey-449hSdqNTPn2zQZaLQ

**Comment by hansmrtn** [comment]
For clarity: 

On Candidates, Participants: 
- Participants are _voters_ (will be renamed to Voters)
- Candidates are those that are being voted on
- A candidate is _not_ automatically a participant(voter) 

let me know if anything else needs a quick explanation

**Comment by naz3eh** [comment]
@hansmrtn Do I have to implement the tooltips that show messages on _hover_ ([demo](https://bddeu.csb.app/)) or the onboarding guide like [here](https://react-joyride.com/)?

Also, can I get little bit more info on the messages to be shown?

**Comment by hansmrtn** [comment]
On hover, outlined here: https://chakra-ui.com/docs/overlay/tooltip
