### ISSUE TITLE
UI: receipts component

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#65]
The JSON document of a party includes a "receipts" array that houses all the payments made in a party. We need a component that can be displayed on the party route that shows when and how much was paid by who.

**Comment by wkarshat** [comment]
ReceiptsTable provides the data structure, but need the display?
Displaying the list of recipients with amounts or the sender and the total, or both?
The date for the disbursement already in the DB?
GFI candidate?
