### ISSUE TITLE
Home Party Card filtering

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#68]
**Is your feature request related to a problem? Please describe.**
This feature is for filtering the home screen party cards to relevant ones that a connected account is participating in.

**Describe the solution you'd like**
It'd be great to have a checkbox, or tab module, or search that allows the user to toggle between all parties and ones they're participating in or are candidates in.

**Comment by wkarshat** [comment]
Reverse chronological order [newest first] would be a good default, by the time there are hundreds.
What does the query look like, to search among the voters, candidates, and creators?
