### ISSUE TITLE
Distributor Contract Tests

### ISSUE THREAD

**Issue by hansmrtn** [moonshotcollective/quadratic-diplomacy#70]
A full-coverage test script is necessary, before we make any changes to the existing "Distributor" contract. 

- [x] deployment
- [x] distributeEther 
- [x] distributeToken
- [ ] correct distribution with various "manual" strategies 
- [ ] etc

We can then accept PRs into the contract, if they pass the test suite.

**Comment by wkarshat** [comment]
What kinda test setup would you like to use?
@codenamejason, are there any implementations of tests currently within Scaffold branches or *Party projects, that we can crib from?
